"""empty message

Revision ID: 2e10ae8bfe9a
Revises: d34b484d2965
Create Date: 2023-11-11 21:36:38.338412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e10ae8bfe9a'
down_revision = 'd34b484d2965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akunName', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('akunID', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['akunID'], ['akun.id'], ),
    sa.ForeignKeyConstraint(['akunName'], ['akun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_akun_transaction_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_akun_transaction_id'))

    op.drop_table('akun_transaction')
    # ### end Alembic commands ###
