"""empty message

Revision ID: 4b17f25b98db
Revises: 340245f6480f
Create Date: 2023-11-06 19:37:12.334775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b17f25b98db'
down_revision = '340245f6480f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_index('ix_product_size_id')

    op.drop_table('product_size')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')

    op.create_table('product_size',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productSize', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('productSizePrice', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('productID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], name='product_size_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.create_index('ix_product_size_id', ['id'], unique=False)

    # ### end Alembic commands ###
