"""empty message

Revision ID: 7b014832ab40
Revises: 2e10ae8bfe9a
Create Date: 2023-11-11 21:37:49.928636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b014832ab40'
down_revision = '2e10ae8bfe9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('akun_transaction_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('akun_transaction_ibfk_2', 'akun', ['akunName'], ['id'])

    # ### end Alembic commands ###
