"""empty message

Revision ID: d34b484d2965
Revises: 4b17f25b98db
Create Date: 2023-11-11 20:38:39.588506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34b484d2965'
down_revision = '4b17f25b98db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun',
    sa.Column('id', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('akun')
    # ### end Alembic commands ###
