"""empty message

Revision ID: f3a1f3afb73e
Revises: 7b014832ab40
Create Date: 2023-11-12 02:27:41.985190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a1f3afb73e'
down_revision = '7b014832ab40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akun_transaction', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
